name: Run Flask App

on:
  push:
    branches:
      - test1
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Run app
      run: |
        python app.py &
        sleep 10  # Wait for the server to start
        kill %1  # Stop the server
